version: "3.8"

services:
  postgres:
    container_name: reetcode-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "reetcode"
      POSTGRES_USER: "reetcode"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    expose:
      - 5432

  problems_api:
    container_name: reetcode-problems-api
    build:
      context: ./api
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - 4400:4400
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    container_name: reetcode-nextjs
    build:
      context: .
      target: dev
    restart: always
    command: npm run docker:dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
